version: '3'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 5432:5432
    volumes:
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql